server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: Freight
          uri: http://localhost:8082
          predicates:
            - Path=/freights/**, 
        - id: Delivery
          uri: http://localhost:8083
          predicates:
            - Path=/freightDeliveries/**, 
        - id: Settlement
          uri: http://localhost:8084
          predicates:
            - Path=/settlements/**, 
        - id: Arlim
          uri: http://localhost:8085
          predicates:
            - Path=/notifications/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Freight
          uri: http://freight:8080
          predicates:
            - Path=/freights/**, 
        - id: Delivery
          uri: http://delivery:8080
          predicates:
            - Path=/freightDeliveries/**, 
        - id: Settlement
          uri: http://settlement:8080
          predicates:
            - Path=/settlements/**, 
        - id: Arlim
          uri: http://arlim:8080
          predicates:
            - Path=/notifications/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
