---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Freight
  labels:
    app: Freight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Freight
  template:
    metadata:
      labels:
        app: Freight
    spec:
      containers:
        - name: Freight
          image: username/Freight:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Delivery
  labels:
    app: Delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Delivery
  template:
    metadata:
      labels:
        app: Delivery
    spec:
      containers:
        - name: Delivery
          image: username/Delivery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Settlement
  labels:
    app: Settlement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Settlement
  template:
    metadata:
      labels:
        app: Settlement
    spec:
      containers:
        - name: Settlement
          image: username/Settlement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Arlim
  labels:
    app: Arlim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Arlim
  template:
    metadata:
      labels:
        app: Arlim
    spec:
      containers:
        - name: Arlim
          image: username/Arlim:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Freight
  labels:
    app: Freight
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Freight


---


apiVersion: v1
kind: Service
metadata:
  name: Delivery
  labels:
    app: Delivery
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Delivery


---


apiVersion: v1
kind: Service
metadata:
  name: Settlement
  labels:
    app: Settlement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Settlement


---


apiVersion: v1
kind: Service
metadata:
  name: Arlim
  labels:
    app: Arlim
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Arlim

